spring.application.name=shopping-website
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.app.jwt.secreatkey=${JWT_SECRET}

spring.app.razorpay.key=${RAZORPAY_KEY}
spring.app.razorpay.secreatkey=${RAZORPAY_SECRET}

spring.app.razorpay.webhooksecret=${RAZORPAY_WEBHOOK_SECRET}